name: Build and Push CPU Stress Container
on:
  push:
    branches:
      - main
    paths:
      - 'docker/Dockerfile.stress'
      - 'src/stress.sh'
      - '.github/workflows/build-stress.yml'

jobs:
  build:
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Docker Login
      run: |
            docker login -u ${{ secrets.ACR_DEV_USERNAME }} https://${{ secrets.ACR_DEV_USERNAME }}.azurecr.io -p ${{ secrets.ACR_DEV_PASSWORD }}
    - name: Docker Build
      run: |
          docker build -f docker/Dockerfile.stress -t someregistry.azurecr.io/alw/kubestress:${GITHUB_RUN_ID} .
          docker tag someregistry.azurecr.io/alw/kubestress:${GITHUB_RUN_ID} someregistry.azurecr.io/alw/kubestress:latest
    - name: Docker Push
      run: |
          docker push someregistry.azurecr.io/alw/kubestress:${GITHUB_RUN_ID}
          docker push someregistry.azurecr.io/alw/kubestress:latest
